INSERT INTO pmo.header_field_mapping (entity_name, header_name, entity_field_name, active)
VALUES
('BR_DATA', 'Auto req ID', 'autoReqId', true),
('BR_DATA', 'Current Req Status', 'currentReqStatus', true),
('BR_DATA', 'Grade', 'grade', true),
('BR_DATA', 'Designation', 'designation', true),
('BR_DATA', 'Recruiter', 'recruiter', true),
('BR_DATA', 'Client Interview?', 'clientInterview', true),
('BR_DATA', 'Mandatory Skills', 'mandatorySkills', true),
('BR_DATA', 'Entity', 'entity', true),
('BR_DATA', 'Client Name', 'clientName', true),
('BR_DATA', 'Billing Type', 'billingType', true),
('BR_DATA', 'Project', 'project', true),
('BR_DATA', 'Requester ID', 'requesterId', true),
('BR_DATA', 'TAG Manager', 'tagManager', true),
('BR_DATA', 'RM Name', 'rmName', true),
('BR_DATA', 'Job description', 'jobDescription', true),
('BR_DATA', 'Joining Location', 'joiningLocation', true),
('BR_DATA', 'Backfill for Employee Name', 'backfillForEmployeeName', true),
('BR_DATA', 'Date Approved', 'dateApproved', true),
('BR_DATA', 'No. of Positions', 'noOfPositions', true),
('BR_DATA', 'Positions Remaining', 'positionsRemaining', true),
('BR_DATA', 'Sourcing Type', 'sourcingType', true),
('BR_DATA', 'Requirement Type', 'requirementType', true),
('BR_DATA', 'ST (Bill Rate) Enter only numeric value and 0 for Non-Billable', 'stBillRate', true);


INSERT INTO pmo.header_field_mapping (entity_name, header_name, entity_field_name, active)
VALUES
('EMPLOYEE', 'Emp No', 'empNo', true),
('EMPLOYEE', 'Emp Name', 'empName', true),
('EMPLOYEE', 'Grade', 'grade', true),
('EMPLOYEE', 'Cumulative Rating', 'cumulativeRating', true),
('EMPLOYEE', 'Appraisal Rating', 'appraisalRating', true),
('EMPLOYEE', 'Previous RM Name', 'previousRmName', true),
('EMPLOYEE', 'Designation', 'designation', true),
('EMPLOYEE', 'Official Mail ID', 'officialMailId', true),
('EMPLOYEE', 'Phone Number', 'phoneNumber', true),
('EMPLOYEE', 'Business Unit', 'businessUnit', true),
('EMPLOYEE', 'Client', 'previousClient', true),
('EMPLOYEE', 'BU', 'businessUnit', true),
('EMPLOYEE', 'SBU', 'businessUnit', true),
('EMPLOYEE', 'Top 3 Skills', 'top3Skills', true),
('EMPLOYEE', 'Rating out of 10 for Top 3 Skills', 'ratingOutOf10ForTop3Skills', true),
('EMPLOYEE', 'Skills Category', 'skillsCategory', true),
('EMPLOYEE', 'Skills Bucket', 'skillsBucket', true),
('EMPLOYEE', 'Detailed Skills', 'detailedSkills', true),
('EMPLOYEE', 'Infinite DOJ', 'infiniteDoj', true),
('EMPLOYEE', 'Received Date', 'receivedDate', true),
('EMPLOYEE', 'LWD', 'lwd', true),
('EMPLOYEE', 'Status', 'status', true),
('EMPLOYEE', 'Remarks', 'remarks', true),
('EMPLOYEE', 'Deployed/Exit Month', 'deployedExitMonth', true),
('EMPLOYEE', 'Deployed/Exit Date-1', 'deployedExitDate1', true),
('EMPLOYEE', 'Deployed Client', 'deployedClient', true),
('EMPLOYEE', 'Reason for Movement to Corp Pool', 'reasonForMovementToCorpPool', true),
('EMPLOYEE', 'Current Location', 'currentLocation', true),
('EMPLOYEE', 'Preferred Location', 'preferredLocation', true),
('EMPLOYEE', 'Office Location', 'officeLocation', true);